//
//  GameData.h
//  GameJam1
//
//  Created by Gabriel Lumbi on 2014-03-23.
//
//

#ifndef GameJam1_GameData_h
#define GameJam1_GameData_h

#define TEXT_MOUTH_CLOSED @"packman_closed.png"
#define TEXT_MOUTH_OPEN @"packman_open.png"

#define TEXT_CHILDREN_MOUTH_CLOSED @"child%u_closed"
#define TEXT_CHILDREN_MOUTH_OPEN @"child%u_open"

#define INIT_FOOD_SPAWN_INTERVAL 0.5f
#define INIT_FOOD_LIMIT 10.0f

#define GYROSCOPE_INTERVAL_UPDATE 0.1f

#define FOOD_EAT_ANIMATION_SCALE_TO 0.0f
#define FOOD_EAT_ANIMATION_SCALE_TO_DURATION 0.5f

#define FOOD_SPAWN_ANIMATION_SCALE_1 1.2f
#define FOOD_SPAWN_ANIMATION_SCALE_2 0.8f
#define FOOD_SPAWN_ANIMATION_SCALE_1_DURATION 0.25f
#define FOOD_SPAWN_ANIMATION_SCALE_2_DURATION 0.25f
#define FOOD_SPAWN_ANIMATION_SCALE_RESTORE_DURATION 0.25f

#define STOMACH_BAR_SCALE_ANIMATION_DURATION 0.25f

#define FEEDER_FOOD_ACCUMULATOR_DECREASE_RATE 1.0f

#define DEFAULT_VOMIT_EMIT_INTERVAL 0.2f
#define VOMIT_RADIUS 30

#endif
